### PR TITLE
adding changes to views, urls, templates, and images to readme

### PR DESCRIPTION
**Pull request by jasondoze**
added renders to views.py, titles to html templates, paths in url patterns, and and image folder to read me with 2 screenshots. all pages are functional but all pages still have a heading of 'landing page'

### CODE REVIEW

**Review by lavoing5762 — COMMENTED** [review]
Not sure how to reconcile models with views.

**Review by LaTonia-Mertica — APPROVED** [review]
Looks good, thanks

**Comment by lavoing5762** [comment]
Looks good

**Review by LaTonia-Mertica — APPROVED** [review]
Trying again ...

**Review by lavoing5762 — APPROVED** [review]
Looks good

**Pull request merged**
