### PR TITLE
added hyperlinks to buttons and updates to views and url patterns 

### PR DESCRIPTION
**Pull request by jasondoze**
added hyperlinks to buttons and updates to views and url patterns for all pages to work and link together through html buttons

### CODE REVIEW

**Review by LaTonia-Mertica — DISMISSED** [review]
Excellent as always, thanks for vesting time and energy to fix this and get all updated ...

**Review by lavoing5762 — DISMISSED** [review]
Good job.

**Review by LaTonia-Mertica — APPROVED** [review]
Thank you

**Review by lavoing5762 — APPROVED** [review]
Looks good.

**Pull request merged**
