### PR TITLE
Created Django project/app and templates directory with basic template files ...

### PR DESCRIPTION
**Pull request by LaTonia-Mertica**
to hopefully get us in a solid position for coding given Tuesdays are now earmarked for non-WOW workshop days. Apologies if I seem over eager @lavoing5762 and @Jason-Doze ... just trying to help and know we still need to get through housekeeping stuff before can really focus on going forward. Please approve and merge ... talk soon 💯

### CODE REVIEW

**Comment by Jason-Doze** [comment]
looks good, making progress!

**Review by jasondoze — APPROVED** [review]
looks good! thanks @LaTonia-Mertica

**Comment by LaTonia-Mertica** [comment]
Thank you - appreciate it .. see you later ... maybe ...
*___________________________________________*
*La'Tonia Mertica*
(Luh Tone Yuh Merr Treece)
*Founder & Executive Officer*

La'Tonia Mertica 'Communications & Creatives Specialist'
<https://mailchi.mp/50361129f72d/latoniamertica>

2200 South Salina Street #684
Syracuse, New York 13205
***@***.***

**Review by lavoing5762 — APPROVED** [review]
Great.

**Pull request merged**
